### ISSUE TITLE
Question - Is there a reason why Kubec policies are not in folders like CIS policies

### ISSUE THREAD

**Issue by mveitas** [raspbernetes/k8s-security-policies#18]
**Describe the solution you'd like:**
First, thank you for the great library of policies!!!

Is there a reason why the kubesec policies are not in their own folders similar to the CIS policies? From a consistency standpoint it makes it easier to just point to a folder if using something like `konstraint` to generate CRDs for gatekeeper. I am more than happy to create a PR to do the work and create the folders

**Comment by saurabhpandit** [comment]
Thanks @mveitas for reaching out.
I totally agree that kubesec policies should be in their own folder, there is no good reason why they are not currently.
We are also considering versioning and packaging the policies so that they can be used in pipelines outside of this repo.
